name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 9,16 */1 * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: test commit checkout
        uses: actions/checkout@v3

      - name: test commit
        run: |
          git config --local user.email "nenerzm@gmail.com"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "test:  test  by ${{ github.actor }} sha ${{github.sha}} tp ${{github.run_attempt}}"
          git push
